### PR TITLE
Fused elementwise normalization

### PR DESCRIPTION
**Pull request by guangzlu**
I had accidentally merged #468 , and I had revert the merge in #491.
So I want to open this PR for continuing merge Fused elementwise normalization.

### CODE REVIEW

**Review by rocking5566 — DISMISSED** [review]
LGTM.
Because this is recreated PR.
Previous comment is here https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/468

**Comment by asroy** [comment]
@guangzlu This PR is not tested by CI
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2Fcomposable_kernel/pr/

**Comment by guangzlu** [comment]
> @guangzlu This PR has not been tested by CI. CK CI will only automatically test branch that is in CK repo. Since this PR's branch is from a forked repo, it will not be tested by CI automatically.
> 
> You would need to start the CI manually here: http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2Fcomposable_kernel/pr/
> 
> I just started the test manually. Please keep monitoring the CI until it passes

OK, I will monitor it, thank you very much!

**Comment by guangzlu** [comment]
> 

Hi @asroy, I think the CI have passed. 
Really thank you for helping me test and telling me about the things of CI.

**Comment by asroy** [comment]
@guangzlu Pleaes resolve merge conflict, and push it through CI, then we can merge this PR

**Review by rocking5566 — APPROVED** [review]
LGTM

**Comment by guangzlu** [comment]
Hi @asroy , I have resolved the conflict, and pushed it through CI, I think it is passed now.

**Pull request merged**
