### PR TITLE
GroupedGEMM + Gelu client example/instances/profiler

### PR DESCRIPTION
**Pull request by aosewski**

### CODE REVIEW

**Comment by aosewski** [comment]
@zjing14 I made an ugly workaround here: https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/614/files#diff-a70ed1b4ce89156976363d77a61cb8e7d0dd8478933c85bd28d10c156a4ca5e3R243-R247 since I got big errors like:
```
Error: Incorrect results!        out[28] != ref[28]: -0.004394531 != -0.002017975                                                                                                                                                             
Error: Incorrect results!        out[31] != ref[31]: 1.955078 != 1.904297                                                                                                                                                                     
Error: Incorrect results!        out[210] != ref[210]: 0.8413086 != 0.6728516                                                                                                                                                                 
Error: Incorrect results!        out[222] != ref[222]: -0.04541016 != -0.02192688                                                                                                                                                             
   max err: 0.168457 
```
But `grouped_gemm` alone works correctly, so this is caused by Gelu itself. Is it expected?

**Comment by aosewski** [comment]
@zjing14  I have updated the example with comments from meeting. The code using `FastGelu` still produces errors...

**Comment by zjing14** [comment]
@aosewski Can you try other elementwise ops, i.e., relu?

**Comment by zjing14** [comment]
@aosewski That is strange. Could you test the regular with Gelu and FastGelu?

**Comment by aosewski** [comment]
@zjing14  I've found a bug in ckProfiler code. Shame on me :P I've run output elementwise op twice. Now it's working correctly both with `Gelu` and `FastGelu`.

**Review by zjing14 — APPROVED** [review]

**Pull request merged**
