### PR TITLE
adding the first draft of changelog

### PR DESCRIPTION
**Pull request by illsilin**
Please feel free to add more contents as needed.

In the future, every time you make a major commit, you should add a line about it in the changelog.md file.

### CODE REVIEW

**Review by geyyer — APPROVED** [review]
LGTM! Let's get it started!

**Comment by aosewski** [comment]
@illsilin What do you think about adding PR# for each bullet in Changelog?

**Comment by illsilin** [comment]
I personally think adding the PR# or commit hash to the changelog would be useful. But the instruction was to create the changelog following the same format as other ROCM libraries, e.g. rocFFT: 

https://github.com/ROCmSoftwarePlatform/rocFFT/blob/develop/CHANGELOG.md

I'll check with Jun or whoever is in charge of this what they think.

**Comment by illsilin** [comment]
OK, sounds like we can add the PR# or commit hash if we like.

**Review by zjing14 — APPROVED** [review]
LGTM

**Pull request merged**
