### PR TITLE
Introduce ck::utils::to_array()

### PR DESCRIPTION
**Pull request by poyenc**
We can use this utility to convert range to [`std::array<>`](https://en.cppreference.com/w/cpp/container/array) or C-array to `std::array<>`. Unlike [`std::to_array()`](https://en.cppreference.com/w/cpp/container/array/to_array) (_C++20_), the input & output element types can be totally different.

```c++
void test(std::array<unsigned, 2>);

test(ck::utils::to_array({1, 2}));                     // ok
test(ck::utils::to_array({4, 5, 6}));                  // oops! wrong # of arguments
test(ck::utils::to_array(std::vector<double>{7.}));    // ok, leave element at [1] uninitialized
test(ck::utils::to_array(std::vector<int>{8, 9, 10})); // ok, 10 is ignored
test(ck::utils::to_array(std::vector<std::string>{})); // oops! trigger assertion failure
```

**[NOTICE]**
This PR requires changes from #442 & #444

### CODE REVIEW

**Review by aosewski — COMMENTED** [review]
I'm not sure if the "copy to bound" behavior is correct. I imagine it may cause developer's surprise and confusion in some situations. 
Moreover some UT, which will be also an usage example (similar to the one in PR description) would be very nice to see I think.

**Comment by poyenc** [comment]
> I'm not sure if the "copy to bound" behavior is correct. I imagine it may cause developer's surprise and confusion in some situations. Moreover some UT, which will be also an usage example (similar to the one in PR description) would be very nice to see I think.

@aosewski maybe we can just leave the _array-to-array_ conversion? like the `std::to_array()` does. To avoid confusion.

**Comment by aosewski** [comment]
> maybe we can just leave the _array-to-array_ conversion? like the `std::to_array()` does. To avoid confusion.

I think that would be clearer behavior.

**Comment by poyenc** [comment]
May using similar utilitites like `std::to_array()` is enough.

**Pull request closed without merging**
