### PR TITLE
Add int4 reduction examples

### PR DESCRIPTION
**Pull request by qianfengz**
Simple int4 support example:
1) Host tensor is initialized in `int4_t`  values
2) Device Tensor represents the values in `int8_t` (So that the current Threadwise/Blockwise data transfer interfaces used by the kernel need not be touched)
3) Calculation is done in `int32_t` or `int8_t`

### CODE REVIEW

**Comment by asroy** [comment]
@qianfengz CI failure

**Comment by asroy** [comment]
@rosenrodt strange BMM+Softmax+BMM failure, maybe missing synchronization somewhere? 

image

**Comment by rosenrodt** [comment]
> @rosenrodt strange BMM+Softmax+BMM failure, maybe missing synchronization somewhere?
> 
> image

I'll look into it. What's more concerning to me is it doesn't seem like a sync issue but a numerical stability issue perhaps? All 4 instances running on the same problem give exact wrong single data point out[93576] `out[93576] != ref[93576]: 0.02172852 != 0.02287292`.

```
[2022-08-24T12:17:43.539Z] a_g_m_k: dim 3, lengths {1, 1024, 128}, strides {131072, 128, 1}
[2022-08-24T12:17:43.539Z] b0_g_k_n: dim 3, lengths {1, 128, 1024}, strides {131072, 1, 128}
[2022-08-24T12:17:43.539Z] b1_g_n_o: dim 3, lengths {1, 1024, 128}, strides {131072, 128, 1}
[2022-08-24T12:17:43.539Z] c_g_m_o: dim 3, lengths {1, 1024, 128}, strides {131072, 128, 1}
[2022-08-24T12:17:43.539Z] found 4 instances
[2022-08-24T12:17:43.539Z] Perf: 0 ms, inf TFlops, inf GB/s, DeviceBatchedGemmSoftmaxGemm_Xdl_CShuffle<256, 256, 128, 32, 8, 8, 256, 128, 32, 2>
[2022-08-24T12:17:43.539Z] Error: Incorrect results!        out[93576] != ref[93576]: 0.02172852 != 0.02287292
[2022-08-24T12:17:43.539Z]    max err: 0.001144409
[2022-08-24T12:17:43.539Z] Perf: 0 ms, inf TFlops, inf GB/s, DeviceBatchedGemmSoftmaxGemm_Xdl_CShuffle<256, 128, 128, 32, 8, 8, 128, 128, 32, 2>
[2022-08-24T12:17:43.539Z] Error: Incorrect results!        out[93576] != ref[93576]: 0.02172852 != 0.02287292
[2022-08-24T12:17:43.539Z]    max err: 0.001144409
[2022-08-24T12:17:43.539Z] Perf: 0 ms, inf TFlops, inf GB/s, DeviceBatchedGemmSoftmaxGemm_Xdl_CShuffle<256, 128, 128, 32, 8, 8, 128, 64, 32, 2>
[2022-08-24T12:17:43.539Z] Error: Incorrect results!        out[93576] != ref[93576]: 0.02172852 != 0.02287292
[2022-08-24T12:17:43.539Z]    max err: 0.001144409
[2022-08-24T12:17:43.539Z] Perf: 0 ms, inf TFlops, inf GB/s, DeviceBatchedGemmSoftmaxGemm_Xdl_CShuffle<256, 128, 64, 32, 8, 8, 128, 128, 32, 2>
[2022-08-24T12:17:43.539Z] Error: Incorrect results!        out[93576] != ref[93576]: 0.02172852 != 0.02287292
[2022-08-24T12:17:43.539Z]    max err: 0.00114440
```

**Comment by rosenrodt** [comment]
I am unable to reproduce error locally on gfx908 and gfx90a. Restarted CI and the error seemed gone.

**Review by asroy — APPROVED** [review]

**Pull request merged**
