### PR TITLE
[WIP] Grouped Gemm + Reduction & Grouped Gemm + Softmax

### PR DESCRIPTION
**Pull request by danyao12**
add groupgemm+reduce&groupgemm+softmax kernel

### CODE REVIEW

**Comment by asroy** [comment]
@danyao12 There is error msg when I tried to build ```example_grouped_gemm_softmax_xdl_fp16```
image

**Comment by danyao12** [comment]
> commented

I merge with the current latest codes and clang-format-10 the codes, please try again.

**Comment by rosenrodt** [comment]
@danyao12 I will get some time to review this in the next week or so

**Comment by asroy** [comment]
no longer pursued

**Pull request closed without merging**
