### PR TITLE
GEMM pipeline v2

### PR DESCRIPTION
**Pull request by poyenc**
This is same PR as #306 but using branch from this repository

### CODE REVIEW

**Comment by poyenc** [comment]
As @shaojiewang has mentioned in #306

> Maybe we still need V1 pipeline as default, because it can apply 2-wave's strategy.

**Comment by poyenc** [comment]
looks like the code itself is fine, but Jenkins kills the job due to build timeout.

**Comment by poyenc** [comment]
> As @shaojiewang has mentioned in #306:
> 
> > Maybe we still need V1 pipeline as default, because it can apply 2-wave's strategy.

I'll make v1 pipeline as default after current code pass all the CI checks

**Comment by shaojiewang** [comment]
> > As @shaojiewang has mentioned in #306:
> > > Maybe we still need V1 pipeline as default, because it can apply 2-wave's strategy.
> 
> I'll make v1 pipeline as default after current code pass all the CI checks

sure, no problem.

**Comment by poyenc** [comment]
How to avoid following compiler error?
```
fatal error: error in backend: SmallVector unable to grow. Requested capacity (4294967296) is larger than maximum value for size type (4294967295)
```

**Comment by shaojiewang** [comment]
> How to avoid following compiler error?
> 
> ```
> fatal error: error in backend: SmallVector unable to grow. Requested capacity (4294967296) is larger than maximum value for size type (4294967295)
> ```

@ltqin has issued a JIRA ticket.

**Comment by poyenc** [comment]
> > How to avoid following compiler error?
> > ```
> > fatal error: error in backend: SmallVector unable to grow. Requested capacity (4294967296) is larger than maximum value for size type (4294967295)
> > ```
> 
> @ltqin has issued a JIRA ticket.

@shaojiewang so we can ignore it then?

**Comment by poyenc** [comment]
> > > > How to avoid following compiler error?
> > > > ```
> > > > fatal error: error in backend: SmallVector unable to grow. Requested capacity (4294967296) is larger than maximum value for size type (4294967295)
> > > > ```
> > > 
> > > 
> > > @ltqin has issued a JIRA ticket.
> > 
> > 
> > @shaojiewang so we can ignore it then?
> 
> @poyenc Unfortunately no. Does this error occur with 9110?

@asroy No, 9110 does successfully build all the targets.

**Review by asroy — APPROVED** [review]

**Review by shaojiewang — APPROVED** [review]

**Comment by shaojiewang** [comment]
So the PR is just blocked by the ```SmallVector``` now?

**Comment by asroy** [comment]
> So the PR is just blocked by the `SmallVector` now?

I removed some codes, including producer & consumer pipeline. I don't see "SmallVector" issue anymore

**Pull request merged**
