### PR TITLE
Create MIT LICENSE

### PR DESCRIPTION
**Pull request by asroy**

### CODE REVIEW

**Comment by asroy** [comment]
> Looks fine. Shall we put it into every cpp and hpp file later?

Yes, need a script or something to do it, but I don't know how to write the script yet.

**Comment by aosewski** [comment]
>

**Comment by aosewski** [comment]
>

IMHO writing a script in python would be the easiest way.

**Review by zjing14 — DISMISSED** [review]

**Comment by asroy** [comment]
opened a new license file PR #292

**Review by zjing14 — APPROVED** [review]

**Pull request merged**
